from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_cors import CORS
from config.config import Config

db      = SQLAlchemy()
migrate = Migrate()


def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)

    # Extensions
    db.init_app(app)
    migrate.init_app(app, db)
    CORS(app, resources={r"/api/*": {"origins": app.config.get('CORS_ORIGINS', '*')}})

    # Initialise read-only blockchain service
    with app.app_context():
        from app.services.blockchain_service import blockchain_service
        try:
            blockchain_service.initialize(
                rpc_url          = app.config['BLOCKCHAIN_RPC_URL'],
                contract_address = app.config['CONTRACT_ADDRESS'],
                contract_abi     = _get_contract_abi(),
            )
            print("✓ Blockchain service ready (read-only)")
        except Exception as e:
            # Non-fatal: the app can still serve requests that don't need the chain
            print(f"✗ Blockchain service failed to initialise: {e}")
            print("  Start the Hardhat node and check CONTRACT_ADDRESS in .env")

    # Blueprints way to organise routes, reusable components
    from app.routes.user_routes    import user_bp
    from app.routes.product_routes import product_bp

    prefix = app.config.get('API_PREFIX', '/api/v1')
    app.register_blueprint(user_bp,    url_prefix=prefix)
    app.register_blueprint(product_bp, url_prefix=prefix)

    # ── Health check ─────────────────────────────────────────
    @app.route('/health')
    def health():
        from app.services.blockchain_service import blockchain_service as bs
        chain_ok = bool(bs.w3 and bs.w3.is_connected())
        return {
            'status':     'ok',
            'database':   'connected',
            'blockchain': 'connected' if chain_ok else 'disconnected',
        }

    @app.route('/')
    def index():
        return {
            'name':    'Supply Chain DApp API',
            'version': '2.0.0',
            'note':    'Write transactions are signed by MetaMask — this API is read + metadata only',
        }

    return app


def _get_contract_abi():
    """ABI for SupplyChain.sol — generated by Hardhat compile."""
    return [
        {"anonymous": False, "inputs": [{"indexed": False, "internalType": "uint256", "name": "id", "type": "uint256"}, {"indexed": False, "internalType": "address", "name": "previousOwner", "type": "address"}, {"indexed": False, "internalType": "address", "name": "newOwner", "type": "address"}], "name": "OwnershipTransferred", "type": "event"},
        {"anonymous": False, "inputs": [{"indexed": False, "internalType": "uint256", "name": "id", "type": "uint256"}, {"indexed": False, "internalType": "string", "name": "name", "type": "string"}, {"indexed": False, "internalType": "address", "name": "owner", "type": "address"}], "name": "ProductRegistered", "type": "event"},
        {"anonymous": False, "inputs": [{"indexed": False, "internalType": "uint256", "name": "id", "type": "uint256"}, {"indexed": False, "internalType": "enum SupplyChain.Stage", "name": "stage", "type": "uint8"}, {"indexed": False, "internalType": "address", "name": "updater", "type": "address"}], "name": "StageUpdated", "type": "event"},
        {"inputs": [{"internalType": "uint256", "name": "id", "type": "uint256"}, {"internalType": "string", "name": "name", "type": "string"}], "name": "RegisterProduct", "outputs": [], "stateMutability": "nonpayable", "type": "function"},
        {"inputs": [{"internalType": "address", "name": "user", "type": "address"}, {"internalType": "enum SupplyChain.Role", "name": "role", "type": "uint8"}], "name": "assignRole", "outputs": [], "stateMutability": "nonpayable", "type": "function"},
        {"inputs": [], "name": "contractOwner", "outputs": [{"internalType": "address", "name": "", "type": "address"}], "stateMutability": "view", "type": "function"},
        {"inputs": [{"internalType": "uint256", "name": "id", "type": "uint256"}], "name": "getCurrentStage", "outputs": [{"internalType": "enum SupplyChain.Stage", "name": "", "type": "uint8"}], "stateMutability": "view", "type": "function"},
        {"inputs": [{"internalType": "uint256", "name": "id", "type": "uint256"}], "name": "getProductHistory", "outputs": [{"components": [{"internalType": "enum SupplyChain.Stage", "name": "stage", "type": "uint8"}, {"internalType": "uint256", "name": "timestamp", "type": "uint256"}, {"internalType": "address", "name": "updater", "type": "address"}], "internalType": "struct SupplyChain.StatusUpdate[]", "name": "", "type": "tuple[]"}], "stateMutability": "view", "type": "function"},
        {"inputs": [{"internalType": "address", "name": "user", "type": "address"}], "name": "getRole", "outputs": [{"internalType": "enum SupplyChain.Role", "name": "", "type": "uint8"}], "stateMutability": "view", "type": "function"},
        {"inputs": [{"internalType": "uint256", "name": "", "type": "uint256"}], "name": "products", "outputs": [{"internalType": "uint256", "name": "id", "type": "uint256"}, {"internalType": "string", "name": "name", "type": "string"}, {"internalType": "address", "name": "owner", "type": "address"}], "stateMutability": "view", "type": "function"},
        {"inputs": [{"internalType": "address", "name": "", "type": "address"}], "name": "roles", "outputs": [{"internalType": "enum SupplyChain.Role", "name": "", "type": "uint8"}], "stateMutability": "view", "type": "function"},
        {"inputs": [{"internalType": "uint256", "name": "id", "type": "uint256"}, {"internalType": "address", "name": "newOwner", "type": "address"}], "name": "transferOwnership", "outputs": [], "stateMutability": "nonpayable", "type": "function"},
        {"inputs": [{"internalType": "uint256", "name": "id", "type": "uint256"}, {"internalType": "enum SupplyChain.Stage", "name": "stage", "type": "uint8"}], "name": "updateStage", "outputs": [], "stateMutability": "nonpayable", "type": "function"},
        {"inputs": [{"internalType": "uint256", "name": "id", "type": "uint256"}, {"internalType": "address", "name": "supposedOwner", "type": "address"}], "name": "verifyProduct", "outputs": [{"internalType": "bool", "name": "", "type": "bool"}], "stateMutability": "view", "type": "function"}
    ]
